{"frames":[{"character_number":0,"end_character_number":0,"end_line_number":0,"file":"","func":"read.table(file.path(path, file.names[i]), header = TRUE, sep = \",\", \n    na.string = \"NA\", as.is = TRUE)","line_number":0},{"character_number":0,"end_character_number":0,"end_line_number":0,"file":"","func":"file(file, \"rt\")","line_number":0}],"message":"Error in file(file, \"rt\") : cannot open the connection\n"}